// error line: 4

Main (->)
    def a <- ArrayOf (1, true)
end
